version: '3.8'

services:

  auth:
    image: vrg18/postgrest-auth
    build: .
    restart: always
    ports: [3001:3001]
    #    links: [db, postgrest]
    #    depends_on: [db, postgrest]
    #    networks: [postgres_default]
    tty: true
    environment:
      POSTGREST_AUTH_DB_CONNECTIONSTRING: postgres://uuuuuuuuuuuuuu:ppppppppppppp@db:5432/main_db?sslmode=disable
      POSTGREST_AUTH_DB_ROLES_ANONYMOUS: anonymous
      POSTGREST_AUTH_DB_ROLES_USER: normal_user
      POSTGREST_AUTH_JWT_EXP: 2
      POSTGREST_AUTH_JWT_SECRET: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      POSTGREST_AUTH_APP_NAME: Libera
      POSTGREST_AUTH_APP_LINK: libera.pro
      POSTGREST_AUTH_LINKS_RESET: http://libera.pro:3001/reset/%v
      POSTGREST_AUTH_LINKS_CONFIRM: http://libera.pro:3001/confirm/%v?token=%v
      POSTGREST_AUTH_EMAIL_FROM: libera@internet.ru
      POSTGREST_AUTH_EMAIL_HOST: smtp.mail.ru
      POSTGREST_AUTH_EMAIL_PORT: 465
      POSTGREST_AUTH_EMAIL_AUTH_USER: libera@internet.ru
      POSTGREST_AUTH_EMAIL_AUTH_PASS: xxxxxxxxxxxx
      POSTGREST_AUTH_OAUTH2_STATE: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    container_name: auth

networks:
  default:
    name: postgres_default
